- README.md
Update README so that the currentVersion and targetVersion version expansions match the proposed example update being made from 2.7.0.Final to 3.1.0.Final.
> Update versions to match the proposed update

- recipes/src/main/resources/quarkus-updates/core/3alpha.yaml
Given in most cases, not upgrading will end up with a big failure, I think we can do that for the big 3.x upgrade.
I don't think it's worth doing it after that though.
Created as draft for now, I still need to test a few things.
> Add rules for Quarkiverse upgrades

- recipes/src/main/resources/quarkus-updates/core/3alpha.yaml
See https://github.com/quarkusio/quarkus/pull/31937
> Replace quarkus.jib.labels with quarkus.container-image.labels

- recipes/src/main/resources/quarkus-updates/recipes.properties
See https://github.com/quarkusio/quarkus/pull/32517#issuecomment-1502798110
> Update rewrite plugins to 4.43.0 / 5.39.3

- recipes/src/main/resources/quarkus-updates/core/3alpha.yaml
Some of them still needs work or releases though.
@holly-cummins @maxandersen this is the current status of the Quarkiverse migration.
> Handle Quarkiverse updates

- recipes/src/main/resources/quarkus-updates/core/3alpha.yaml
There is a problem with OpenRewrite preferring Alphas over final versions.
See https://github.com/openrewrite/rewrite/issues/3143
> Update Quarkiverse status and pinpoint versions

- recipes/src/main/resources/quarkus-updates/core/3alpha.yaml
Fixes https://github.com/quarkusio/quarkus/issues/33549
> Rewrite Kotlin allopen entries of pom.xml when upgrading

- recipes/src/main/resources/quarkus-updates/core/3alpha.yaml
- tools/3.0/PropertiesToRecipe.java
Fixes https://github.com/quarkusio/quarkus/issues/33973
> Make changes for javax.transaction non-recursive

- recipes/pom.xml
- recipes/src/main/resources-filtered/quarkus-updates/recipes.properties
- recipes/src/main/resources/quarkus-updates/recipes.properties
Tested on my projects and it seems to work.
> Align versions to OpenRewrite 7.40.8

- recipes-unit-tests/pom.xml
I noticed a dependency, which is not used and can be removed.
> Removing unnecessary dependency

- recipes-unit-tests/src/test/java/io/quarkus/updates/camel30/CamelJmxTest.java
- recipes/src/main/resources/quarkus-updates/org.apache.camel.quarkus/camel-quarkus-core/3alpha.yaml
fixes https://github.com/quarkusio/quarkus-updates/issues/55
> Missing Camel JMX missing recipes

- recipes-unit-tests/src/test/java/io/quarkus/updates/camel30/CameXmlDslRecipeTest.java
- recipes-unit-tests/src/test/java/io/quarkus/updates/camel30/CamelPomRecipeTest.java
- recipes/src/main/java/io/quarkus/updates/camel30/xml/CircuitBreakerXmlDslRecipe.java
- recipes/src/main/resources/quarkus-updates/org.apache.camel.quarkus/camel-quarkus-core/3alpha.yaml
fixes https://github.com/quarkusio/quarkus-updates/issues/57
> Camel-quarkus: recipe for upgrade of circuit breaker XML DSL is missing

- recipes-unit-tests/pom.xml
- recipes/pom.xml
- recipes/src/main/resources/quarkus-updates/core/3.3.yaml
Also clean up the POM files to avoid warnings and confusing configuration
> Rewrite org.graalvm.nativeimage:svm to org.graalvm.sdk:graal-sdk

- recipes-unit-tests/src/test/java/io/quarkus/updates/camel30/CamelHttpTest.java
- recipes/src/main/java/io/quarkus/updates/camel30/java/CamelHttpRecipe.java
fixes https://github.com/quarkusio/quarkus-updates/issues/77
> Fixed import of AthScope #77

- recipes/pom.xml
- recipes/src/main/java/io/quarkus/updates/package-info.java
- recipes/src/main/java/lombok.config
We need Lombok properly running and configured to be able to pass parameters to recipes.
> Support parameters in YAML recipes

- recipes-unit-tests/src/test/java/io/quarkus/updates/core/CoreUpdate37Test.java
- recipes/src/main/java/io/quarkus/updates/core/quarkus37/UpgradeMavenCompilerJavaVersion.java
- recipes/src/main/resources/quarkus-updates/core/3.7.yaml
Contains a workaround for https://github.com/openrewrite/rewrite/pull/3842 .
> Update Maven Compiler Plugin Java version and Maven plugins for Quarkus 3.7

- recipes/src/main/resources/quarkus-updates/core/3.7.alpha1.yaml
We have too many problems with it:
https://github.com/quarkusio/quarkus-updates/issues/121
https://github.com/quarkusio/quarkus/issues/38569
> Drop the recipe to update the Maven wrapper

- .github/quarkus-ecosystem-test
- .github/workflows/build.yml
- .github/workflows/quarkus-snapshot.yaml
- .quarkus/cli/plugins/quarkus-cli-catalog.json
- recipes-tests/src/test/java/io/quarkus/updates/integration/UpdateProjectEcosystemIT.java
- recipes-tests/src/test/java/io/quarkus/updates/integration/UpdateProjectIT.java
- recipes-tests/src/test/resources/update-tests.csv
This introduces snapshot ecosystem CI and increase the xmx to avoid out of memory.
The ecosystem CI is using the snapshot CLI for updates
> Add snapshot ecosystem CI

- recipes-tests/src/test/java/io/quarkus/updates/camel/CamelUpdate44Test.java
- recipes/src/main/resources/quarkus-updates/org.apache.camel.quarkus/camel-quarkus/3.8.yaml
fixes https://github.com/quarkusio/quarkus-updates/issues/151
> Camel 4.4 route-controller migration more formats

- recipes-tests/src/test/java/io/quarkus/updates/camel/CamelUpdate44Test.java
- recipes/src/main/resources/quarkus-updates/org.apache.camel.quarkus/camel-quarkus/3.8.yaml
fixes https://github.com/quarkusio/quarkus-updates/issues/153
> Camel 4.4 - routeController migration should be in camelCase

- README.md
fixes https://github.com/quarkusio/quarkus-updates/issues/180
> Add README section for how to provide extension recipes

- recipes-tests/src/test/java/io/quarkus/updates/camel/CamelQuarkusTestUtil.java
- recipes-tests/src/test/java/io/quarkus/updates/camel/CamelUpdate41Test.java
- recipes-tests/src/test/java/io/quarkus/updates/camel/CamelUpdate42Test.java
- recipes-tests/src/test/java/io/quarkus/updates/camel/CamelUpdate43Test.java
- recipes-tests/src/test/java/io/quarkus/updates/camel/CamelUpdate44Test.java
- recipes-tests/src/test/java/io/quarkus/updates/camel/camel40/CameXmlDslRecipeTest.java
- recipes-tests/src/test/java/io/quarkus/updates/camel/camel40/CamelAPIsPropertiesTest.java
- recipes-tests/src/test/java/io/quarkus/updates/camel/camel40/CamelAPIsTest.java
- recipes-tests/src/test/java/io/quarkus/updates/camel/camel40/CamelBeanRecipeTest.java
- recipes-tests/src/test/java/io/quarkus/updates/camel/camel40/CamelEIPRecipeTest.java
- recipes-tests/src/test/java/io/quarkus/updates/camel/camel40/CamelHttpTest.java
- recipes-tests/src/test/java/io/quarkus/updates/camel/camel40/CamelJmxTest.java
- recipes-tests/src/test/java/io/quarkus/updates/camel/camel40/CamelYamlTest.java
- recipes/src/main/resources/quarkus-updates/org.apache.camel.quarkus/camel-quarkus/3alpha.yaml
fixes https://github.com/quarkusio/quarkus-updates/issues/208
> Proper test environment for the camel-quarkus recipes

- recipes-tests/src/test/java/io/quarkus/updates/core/CoreUpdate319Test.java
- recipes/src/main/resources/quarkus-updates/core/3.19.alpha1.yaml
Related to [#47249](https://github.com/quarkusio/quarkus/issues/47249)
> Rewrite Hibernate ORM validation mode property

- .github/workflows/build.yml
- recipes/src/main/resources/quarkus-updates/core/3.23.alpha1.yaml
Note: I will add tests when we have a CR1 that I can use for testing.
> Migrate Hibernate ORM schema management properties

- pom.xml
This reverts commit 54082dfe60b37594dbb4978331ab07eb475cbe16.
> Revert "Bump org.jboss:jboss-parent from 49 to 50"
