quarkusio/quarkus-updates

recipes/src/main/resources/quarkus-updates/core/3alpha.yaml
OpenRewrite doesn't reload the model and adds the exclusions even if they are gone in Quarkus 3.
=> Remove the exclusions for now

recipes/src/main/resources/quarkus-updates/core/3alpha.yaml
- This enables projects using classes like `com.fasterxml.jackson.rs.yaml.YAMLMediaTypes` to be changed to `com.fasterxml.jackson.jakarta.rs.yaml.YAMLMediaTypes`
=> Update `com.fasterxml.jackson.rs` package to `com.fasterxml.jackson.jakarta.rs`

recipes/src/main/resources/quarkus-updates/core/3alpha.yaml
- Required for https://github.com/quarkusio/quarkus/pull/32186
=> Replace `quarkus-bootstrap-maven-plugin` with `quarkus-extension-maven-plugin`

recipes/pom.xml, recipes/src/main/assembly/core.xml
The `maven-jar-plugin` can only include/exclude resources, but not move them to a different directory in the output folder; the assembly plugin can.
@ia3andy Keep in mind that a similar assembly will have to be provided for every directory under `src/main/resources/quarkus-updates` if it releases in a separate JAR file.
=> Move the core upgrade recipe to a separate JAR

.github/workflows/build.yml, recipes/pom.xml, recipes/src/main/java/io/quarkus/updates/core/quarkus30/AdjustKotlinAllOpenDirectives.java, recipes/src/main/resources/quarkus-updates/core/3alpha.yaml
Once an AST file has been manipulated by a text-based recipe, anything AST on this file gets ignored so we need to get rid of all text manipulations on files adjusted via AST.
=> Switch to AST manipulations instead of using text replacements

recipes/src/main/resources/quarkus-updates/core/3.3.yaml
@yrodiere I let you have a look.
=> Add recipe for 3.3

.github/workflows/build.yml, pom.xml, recipes-unit-tests/pom.xml, recipes-unit-tests/src/test/java/io/quarkus/updates/camel30/CameXmlDslRecipeTest.java, recipes-unit-tests/src/test/java/io/quarkus/updates/camel30/CamelAPIsPropertiesTest.java, recipes-unit-tests/src/test/java/io/quarkus/updates/camel30/CamelAPIsTest.java, recipes-unit-tests/src/test/java/io/quarkus/updates/camel30/CamelBeanRecipeTest.java, recipes-unit-tests/src/test/java/io/quarkus/updates/camel30/CamelEIPRecipeTest.java, recipes-unit-tests/src/test/java/io/quarkus/updates/camel30/CamelHttpTest.java, recipes-unit-tests/src/test/java/io/quarkus/updates/camel30/CamelPomRecipeTest.java, recipes-unit-tests/src/test/java/io/quarkus/updates/camel30/CamelQuarkusTestUtil.java, recipes-unit-tests/src/test/java/io/quarkus/updates/camel30/CamelYamlTest.java, recipes/src/main/java/io/quarkus/updates/camel30/AbstractCamelQuarkusJavaVisitor.java, recipes/src/main/java/io/quarkus/updates/camel30/RecipesUtil.java, recipes/src/main/java/io/quarkus/updates/camel30/java/CamelAPIsRecipe.java, recipes/src/main/java/io/quarkus/updates/camel30/java/CamelBeanRecipe.java, recipes/src/main/java/io/quarkus/updates/camel30/java/CamelEIPRecipe.java, recipes/src/main/java/io/quarkus/updates/camel30/java/CamelHttpRecipe.java, recipes/src/main/java/io/quarkus/updates/camel30/xml/XmlDslRecipe.java, recipes/src/main/java/io/quarkus/updates/camel30/yaml/CamelQuarkusYamlRouteConfigurationSequenceRecipe.java, recipes/src/main/java/io/quarkus/updates/camel30/yaml/CamelQuarkusYamlStepsInFromRecipe.java, recipes/src/main/java/io/quarkus/updates/camel30/yaml/CamelQuarkusYamlVisitor.java, recipes/src/main/java/io/quarkus/updates/camel30/yaml/YamlRecipesUtil.java, recipes/src/main/resources/quarkus-updates/org.apache.camel.quarkus/camel-quarkus-core/3alpha.yaml
**Descripition:**
PR introduces a recipe - org.apache.camel.quarkus.update.CamelQuarkusMigrationRecipe - which takes care of the whole camel-quarkus migration process. This main recipe registeres all other recipes via the constructor and `doNext` method. If the migrated project contains any camel-quarkus dependency, the child recipes are executed. There are 4 types of camel recipes so far:
Java - recipes migrating java classes. Abstract parent of those recipes detects existence of camel-quarkus import and does nothing if there is no such import
Pom - maven recipes taking care of removed extensions (comments helping users to find replacement are created if possible)
Properties - simple recipe
Yaml - some transformation for YAML DSL feature from Camel
All migration cases are covered by …
=> Recipes for camel-quarkus

recipes/src/main/resources/quarkus-updates/core/3.5.yaml
See https://github.com/smallrye/smallrye-mutiny/releases/tag/2.5.0 and https://github.com/smallrye/smallrye-mutiny/pull/1362
Not sure if it belongs here, but I couldn't find any place for Mutiny rewrites itself.
Tested this on one of my local projects and simply rewrites the methods from `combinedWith` to `with` and compiles successfully without any deprecation warnings afterwards with Quarkus 3.5.0
=> Rewrite mutiny deprecation for reworked Uni combination APIs

recipes/src/main/resources/quarkus-updates/core/3.0.yaml
Somehow the classpath has changed and if using the openrewrite names, the original recipes are applied which add all sorts of dependencies we don't want.
=> Rename javax transformation recipes to our own namespace

plugins/pom.xml
There was a note saying this was not possible, but I think it might through the added repository, if that had not been tried already.
=> Track Gradle plugin version just as we do Maven

recipes/src/main/resources/quarkus-updates/core/3.7.yaml
- Required for https://github.com/quarkusio/quarkus/issues/37477
Recipe documentation in https://docs.openrewrite.org/recipes/maven/upgradepluginversion
=> Bump maven-compiler-plugin to 3.12.1

recipes-unit-tests/src/test/java/io/quarkus/updates/core/CoreTestUtil.java, recipes-unit-tests/src/test/java/io/quarkus/updates/core/CoreUpdate37Test.java, recipes/src/main/resources/quarkus-updates/core/3.7.yaml
The test is disabled until we have a 3.7.0 around.
=> Add recipes to rename resteasy-client dependencies

recipes-unit-tests/src/test/java/io/quarkus/updates/core/CoreTestUtil.java, recipes-unit-tests/src/test/java/io/quarkus/updates/core/CoreUpdate37Test.java, recipes-unit-tests/src/test/java/io/quarkus/updates/core/CoreUpdate39Test.java, recipes/src/main/java/io/quarkus/updates/core/quarkus37/AddMavenCompilerAnnotationProcessor.java, recipes/src/main/java/io/quarkus/updates/core/quarkus37/ChangeMavenCompilerAnnotationProcessorGroupIdAndArtifactId.java, recipes/src/main/java/io/quarkus/updates/core/quarkus37/SyncMavenCompilerAnnotationProcessorVersion.java, recipes/src/main/java/io/quarkus/updates/core/quarkus39/RemoveMavenCompilerAnnotationProcessor.java, recipes/src/main/resources/quarkus-updates/core/3.10.yaml, recipes/src/main/resources/quarkus-updates/core/3.11.yaml, recipes/src/main/resources/quarkus-updates/core/3.12.yaml, recipes/src/main/resources/quarkus-updates/core/3.13.yaml, recipes/src/main/resources/quarkus-updates/core/3.7.alpha1.yaml, recipes/src/main/resources/quarkus-updates/core/3.8.yaml, recipes/src/main/resources/quarkus-updates/core/3.9.yaml
/cc @famod @yrodiere 
I think this should do it (and keep the version in sync when people updates to new versions).
=> Enforce the version of the annotation processor for now

recipes-tests/src/test/java/io/quarkus/updates/integration/UpdateProjectIT.java
This is an infrastructure thing and not really related to what we are supposed to test and I already had to tweak it once and now I have: [WARN] Already trusted source(s). No changes made. when trying to release, which doesn't match the assert.
=> Do not assert JBang output

recipes-tests/src/test/java/io/quarkus/updates/camel/camel40/CamelAPIsTest.java, recipes/src/main/java/io/quarkus/updates/camel/camel40/java/CamelAPIsRecipe.java, recipes/src/main/java/io/quarkus/updates/camel/customRecipes/MoveGetterToPluginHelper.java, recipes/src/main/resources/quarkus-updates/org.apache.camel.quarkus/camel-quarkus/3alpha.yaml
fixes https://github.com/quarkusio/quarkus-updates/issues/170
Part of the `CamelAPIRecipe` is refactored to custom recipe (`MoveGetterToPluginHelper.java`), which is registered several times in `3alpha.yaml`
=> Some missing recipes for upgrading to camel 4.0

pom.xml, recipes-tests/pom.xml, recipes-tests/src/test/java/io/quarkus/updates/camel/CamelQuarkusTestUtil.java, recipes-tests/src/test/java/io/quarkus/updates/camel/CamelUpdate41Test.java, recipes-tests/src/test/java/io/quarkus/updates/camel/CamelUpdate42Test.java, recipes-tests/src/test/java/io/quarkus/updates/camel/CamelUpdate43Test.java, recipes-tests/src/test/java/io/quarkus/updates/camel/CamelUpdate44Test.java, recipes-tests/src/test/java/io/quarkus/updates/camel/CamelUpdate45Test.java, recipes-tests/src/test/java/io/quarkus/updates/camel/CamelUpdate46Test.java, recipes-tests/src/test/java/io/quarkus/updates/camel/CamelUpdate47Test.java, recipes-tests/src/test/java/io/quarkus/updates/camel/camel40/CamelAPIsPropertiesTest.java, recipes-tests/src/test/java/io/quarkus/updates/camel/camel40/CamelAPIsTest.java, recipes-tests/src/test/java/io/quarkus/updates/camel/camel40/CamelBeanRecipeTest.java, recipes-tests/src/test/java/io/quarkus/updates/camel/camel40/CamelEIPRecipeTest.java, recipes-tests/src/test/java/io/quarkus/updates/camel/camel40/CamelHttpTest.java, recipes-tests/src/test/java/io/quarkus/updates/camel/camel40/CamelJmxTest.java, recipes-tests/src/test/java/io/quarkus/updates/camel/camel40/CamelYamlTest.java, recipes/pom.xml, recipes/src/main/resources/quarkus-updates/org.apache.camel.quarkus/camel-quarkus/3.15.yaml, recipes/src/main/resources/quarkus-updates/org.apache.camel.quarkus/camel-quarkus/3alpha.yaml
fixes https://github.com/quarkusio/quarkus-updates/issues/219
Upgrade of camel-upgrade-recipes 4.8.0
(with staging repository, therefore this is a draft)
- new recipes for migration to Camel 4.5-4.8 are added
- few test method had to be modified to make sense in Quarkus
- package  used in camel-upgrade-recipes was slightly changed
=> Update camel-upgrade-recipes to 4.8.0

recipes-tests/src/test/java/io/quarkus/updates/core/CoreUpdate318Test.java, recipes/src/main/resources/quarkus-updates/core/3.18.yaml
- This removes the `quarkus.flyway.clean-on-validation-error`. See https://github.com/quarkusio/quarkus/pull/44912
=> Introduce Quarkus 3.18 Migration Scripts

pom.xml, recipes-tests/src/test/java/io/quarkus/updates/camel/camel40/CamelPomRecipeTest.java, recipes/src/main/java/io/quarkus/updates/core/quarkus310/AdjustPackageProperty.java, recipes/src/main/java/io/quarkus/updates/core/quarkus37/ChangeMavenCompilerAnnotationProcessorGroupIdAndArtifactId.java, recipes/src/main/resources/quarkus-updates/core/3.0.yaml, recipes/src/main/resources/quarkus-updates/core/3.7.alpha1.yaml
Following on from 
- https://github.com/openrewrite/rewrite/pull/3843
- https://github.com/openrewrite/rewrite/pull/4421
And especially relevant now with
- https://github.com/openrewrite/rewrite/issues/4902
- Fixes #226
=> Update 3.0.yaml to use `newArtifactId:` instead of deprecated `newArtifact:`

.github/workflows/build.yml, pom.xml, recipes/pom.xml, recipes/src/main/java/io/quarkus/updates/core/quarkus37/SetupJavaUpgradeJavaVersion.java, recipes/src/main/java/io/quarkus/updates/core/quarkus37/UpgradeJavaVersion.java, recipes/src/main/resources/quarkus-updates/core/3.7.alpha1.yaml
Work in progress, as discussed after
- https://github.com/quarkusio/quarkus-updates/pull/236
/cc @gsmet to avoid duplicate work or conflicts
My process for these changes was to look at these specific Apache licensed versions of the recipes
- https://github.com/openrewrite/rewrite-migrate-java/blob/v2.30.1/src/main/java/org/openrewrite/java/migrate/UpgradeJavaVersion.java
- https://github.com/openrewrite/rewrite-github-actions/blob/v2.10.1/src/main/java/org/openrewrite/github/SetupJavaUpgradeJavaVersion.java
Then from there modify them to strip out the call out to modify Jenkins build files for instance, simplify them where arguments are concerned, inline static nested class, and add the result here.
=> Rewrite recipe bom 3.x

recipes-tests/src/test/java/io/quarkus/updates/core/CoreUpdate319Test.java, recipes/src/main/resources/quarkus-updates/core/3.19.alpha1.yaml
Adds a recipe for changes made in https://github.com/quarkusio/quarkus/pull/45923.
=> Add recipe for Quarkus 3.19 that moves OIDC Token Propagation annotation @AccessToken to a new package

pom.xml, recipes-tests/pom.xml, recipes-tests/src/test/java/io/quarkus/updates/camel/CamelQuarkusTestUtil.java, recipes-tests/src/test/java/io/quarkus/updates/camel/CamelUpdate49Test.java, recipes/pom.xml, recipes/src/main/resources/quarkus-updates/org.apache.camel.quarkus/camel-quarkus/3.17.yaml, recipes/src/main/resources/quarkus-updates/org.apache.camel.quarkus/camel-quarkus/3alpha.yaml
Replaces https://github.com/quarkusio/quarkus-updates/pull/249
Camel-upgrade-recipes is updated to to 4.9.0:
- some constants and util classes had to be updated to cover new version
- more jars of the different versions, required to compile tests, are added (i.e. related to https://github.com/apache/camel-upgrade-recipes/commit/bd9c7a92766c542b7006399250ad5d31148eb96e#diff-d90e48a6b59ba036b8a355a209ed46ffe42636ae3dec25c95501d87443ef2c3f)
- I encountered a weird behavior related to import groupings in `CamelUpdate49Test`. As you can see the camel expected test result ([code](https://github.com/apache/camel-upgrade-recipes/blob/main/camel-upgrade-recipes/src/test/java/org/apache/camel/upgrade/CamelUpdate49Test.java#L257-L284)), majority of the import statement stays un-grouped. Whereas in …
=> Bumped camel-upgrade-recipes to 4.9.0 & migration to CQ 3.17

pom.xml, recipes-tests/pom.xml, recipes-tests/src/test/java/io/quarkus/updates/camel/CamelQuarkusTestUtil.java, recipes-tests/src/test/java/io/quarkus/updates/camel/CamelUpdate410Test.java, recipes/src/main/resources/quarkus-updates/org.apache.camel.quarkus/camel-quarkus/3.18.yaml
fixes https://github.com/quarkusio/quarkus-updates/issues/266
Bump of camel-upgrade-recipes and removed workaround in the `CamelUpdate49Test.java`.
=> Bump camel-upgrade-recipes to 4.10.0

recipes/src/main/resources/quarkus-updates/io.quarkiverse.minio/quarkus-minio/3.8.yaml
I found the typo because it breaks OpenRewrites documentation generation.
=> Fix type in Minio 3.8 upade recipes

pom.xml, recipes-tests/src/test/java/io/quarkus/updates/camel/CamelUpdate45Test.java, recipes-tests/src/test/java/io/quarkus/updates/camel/CamelUpdate46Test.java
Replaces https://github.com/quarkusio/quarkus-updates/pull/309
Upgrade of openrewrite to 3.9.0 and camel-upgrade-recipes to 4.12.1
The staging repo commit will be removed once the release is completed. (that's why this PR is draft, to see CI results)
=> Bumped open rewrite and camel recipes

recipes/src/main/resources/quarkus-updates/core/3.26.alpha1.yaml
Currently recipes expect to rewrite the same `oldPropertyKey` into 2 different `newPropertyKey`, which doesn't make sense and I think must had been a typo. Also it doesn't work.
=> Fix update of `quarkus.log.handler.` async enabled flags
